spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://master:3306/mydb
      username: root
      password: root
mybatis:
  base-packages: com.exmample.dao
  type-aliases-package: com.example.dao
  mapper-locations: classpath:mapper/*.xml