package com.example.dao.mapper;

import com.example.dao.model.Blog;
import com.example.dao.model.BlogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    Blog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Blog
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    int updateByPrimaryKey(Blog record);
}