package com.example.dao.model;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.id
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.title
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Blog.content
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.id
     *
     * @return the value of Blog.id
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.id
     *
     * @param id the value for Blog.id
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.title
     *
     * @return the value of Blog.title
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.title
     *
     * @param title the value for Blog.title
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Blog.content
     *
     * @return the value of Blog.content
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Blog.content
     *
     * @param content the value for Blog.content
     *
     * @mbg.generated Sun Sep 15 16:16:20 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}